---
- hosts: persister
  gather_facts: no
  pre_tasks:
    - name: update apt-get
      become: yes
      raw: apt update
#    - name: update apt-get
#      become: yes
#      raw: apt update
#    - name: update apt-get
#      become: yes
#      raw: apt update
#    - name: install python2.7
#      become: yes
#      raw: apt -y install python
    - name: Gathering facts
      setup:
  roles:
#  - node_exporter
  - persister